apiVersion: v1
kind: Pod
metadata:
  name: bookmark-manager-pod
spec:
  containers:
    - name: manager-container
      image: callenengineering/bookmark-manager:latest
      env:
        - name: PORT
          value: "8080"
      ports:
        - containerPort: 8080
